### PR TITLE
Add facet.pivot functionality

### PR DESCRIPTION
**Pull request by ReportMort**
I've written a crude version of something that will return a facet.pivot result as data.frame as part of the returned list from `solr_facet`. This is in reference to Issue: https://github.com/ropensci/solrium/issues/80. Hopefully that's a decent start to work from.

### CODE REVIEW

**Comment by sckott** [comment]
Can you add a description of the `facet.pivot` and `facet.pivot.mincount` params in the `man-roxygen/facet.R`  file https://github.com/ropensci/solrium/blob/master/man-roxygen/facet.r

**Comment by sckott** [comment]
Ah, now I see that you did add param defs, I think manually to the .Rd file, correct?  By including in that template file, when you run document it pulls that in

**Comment by sckott** [comment]
Any advantage to `ldply` over using `dplyr::rbind_all` or `rbind_list()`. `dplyr` is a kinda heavy dependency, but we do already import it.  I imagine dplyr is faster - although that's just a guess - Also, this doesn't necessarily need to be changed, just asking.

**Comment by ReportMort** [comment]
I think I built the documentation .Rd files, but forgot to commit the template documentation `facet.R`. We should be okay now.

No particular preference for using `ldply`. We can change that or revisit if needed, especially since the function still isn't totally complete (doesn't support XML and could probably be written better).

**Comment by sckott** [comment]
Okay, thanks. Let's leave `ldply()` for now

Any reason `pivot_flatten_tabular()` is exported?

**Comment by ReportMort** [comment]
No reason to have `pivot_flatten_tabular()` exported, so I removed that reference. The rest of `solr_facet` leverages `rbind_all()`, so I went ahead and switched to using that instead of `ldply()`. The change will make for one less item in the NAMESPACE.

**Comment by sckott** [comment]
Great, thanks much! LGTM

**Pull request merged**
